const GET_ONE_ROUTE_REQUEST = "GET_ONE_ROUTE_REQUEST"
const GET_ONE_ROUTE_SUCCESS = "GET_ONE_ROUTE_SUCCESS"
const GET_ONE_ROUTE_FAILURE = "GET_ONE_ROUTE_FAILURE"
const GET_ONE_BUS_DATA = "GET_ONE_BUS_DATA"

export {GET_ONE_ROUTE_REQUEST,GET_ONE_ROUTE_SUCCESS,GET_ONE_ROUTE_FAILURE,GET_ONE_BUS_DATA}